import json
from pathlib import Path

PROCESSED = Path("data/processed/transit")

# Load IR records (gold labels)
with open(PROCESSED / "constraint_ir.json") as f:
    ir_records = json.load(f)

# Load generated outputs (SOLAR's CP-SAT code)
with open(PROCESSED / "cpsat_generated_outputs.json") as f:
    generated = json.load(f)

# Index generated by constraint_id
gen_lookup = {r["constraint_id"]: r for r in generated}

# Find constraints with exceptions
with_exceptions = [r for r in ir_records 
                   if r.get("exceptions") and 
                   len(r["exceptions"]) > 0]

print(f"Constraints with exceptions: {len(with_exceptions)}")

# Check how many have OnlyEnforceIf in generated code
grounded = 0
total = 0

for ir in with_exceptions:
    cid = ir["constraint_id"]
    if cid not in gen_lookup:
        continue
    total += 1
    code = gen_lookup[cid].get("generated_code", "")
    if "OnlyEnforceIf" in code or "only_enforce_if" in code.lower():
        grounded += 1

print(f"Total with exceptions: {total}")
print(f"SOLAR grounded (OnlyEnforceIf present): {grounded}")
print(f"SOLAR grounding rate: {grounded/total*100:.1f}%")
print(f"GPT-4o grounding rate: 0% (no CP-SAT output)")
print(f"DeepSeek grounding rate: 0% (no CP-SAT output)")

